// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mnbao1975/microservices/product-api/sdk/models"
)

// ListOneProductReader is a Reader for the ListOneProduct structure.
type ListOneProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOneProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOneProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListOneProductBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListOneProductOK creates a ListOneProductOK with default headers values
func NewListOneProductOK() *ListOneProductOK {
	return &ListOneProductOK{}
}

/* ListOneProductOK describes a response with status code 200, with default header values.

A product returns in the response
*/
type ListOneProductOK struct {
	Payload *models.Product
}

func (o *ListOneProductOK) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listOneProductOK  %+v", 200, o.Payload)
}
func (o *ListOneProductOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *ListOneProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOneProductBadRequest creates a ListOneProductBadRequest with default headers values
func NewListOneProductBadRequest() *ListOneProductBadRequest {
	return &ListOneProductBadRequest{}
}

/* ListOneProductBadRequest describes a response with status code 400, with default header values.

An error returns in the response
*/
type ListOneProductBadRequest struct {
	Payload *models.GenericError
}

func (o *ListOneProductBadRequest) Error() string {
	return fmt.Sprintf("[GET /products/{id}][%d] listOneProductBadRequest  %+v", 400, o.Payload)
}
func (o *ListOneProductBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListOneProductBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
