// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListOneProductParams creates a new ListOneProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListOneProductParams() *ListOneProductParams {
	return &ListOneProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListOneProductParamsWithTimeout creates a new ListOneProductParams object
// with the ability to set a timeout on a request.
func NewListOneProductParamsWithTimeout(timeout time.Duration) *ListOneProductParams {
	return &ListOneProductParams{
		timeout: timeout,
	}
}

// NewListOneProductParamsWithContext creates a new ListOneProductParams object
// with the ability to set a context for a request.
func NewListOneProductParamsWithContext(ctx context.Context) *ListOneProductParams {
	return &ListOneProductParams{
		Context: ctx,
	}
}

// NewListOneProductParamsWithHTTPClient creates a new ListOneProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewListOneProductParamsWithHTTPClient(client *http.Client) *ListOneProductParams {
	return &ListOneProductParams{
		HTTPClient: client,
	}
}

/* ListOneProductParams contains all the parameters to send to the API endpoint
   for the list one product operation.

   Typically these are written to a http.Request.
*/
type ListOneProductParams struct {

	/* ID.

	   The id of product given on the URI path

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list one product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListOneProductParams) WithDefaults() *ListOneProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list one product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListOneProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list one product params
func (o *ListOneProductParams) WithTimeout(timeout time.Duration) *ListOneProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list one product params
func (o *ListOneProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list one product params
func (o *ListOneProductParams) WithContext(ctx context.Context) *ListOneProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list one product params
func (o *ListOneProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list one product params
func (o *ListOneProductParams) WithHTTPClient(client *http.Client) *ListOneProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list one product params
func (o *ListOneProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list one product params
func (o *ListOneProductParams) WithID(id int64) *ListOneProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list one product params
func (o *ListOneProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListOneProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
